detectors:
  - name: SpecialFormatDetector
    keywords:
      - special
    regex:
      format: \s([A-Z]!)+
  - name: MongodbConnectionStringDetector
    keywords:
      - mongo
    regex:
      mongo: mongodb(?:\\+srv)?:\\/\\/(?:[^:\\/?#]*)(?::[^@\\/?#]*)?@[^\\/?#]+(?:\\/[^\\s?#]*)?(?:\\?[^#\\s]*)?(?:#[^\\s]*)?
  - name: WP-ConfigDetector
    keywords:
      - define
    regex:
      wp-format: define(.{0,20})?(NONCE_SALT|LOGGED_IN_SALT|AUTH_SALT|NONCE_KEY|DB_PASSWORD|AUTH_KEY|SECURE_AUTH_KEY|LOGGED_IN_KEY)(.{0,20})?['|\"].{10,120}['|\"]    
